### ISSUE TITLE
Large diameter CNT not modelled properly

### ISSUE THREAD

**Issue by ramanpsingh** [bio-phys/cnt-martini#1]
[cnt-200-50-a470-CNP-f00-SNda.zip](https://github.com/bio-phys/cnt-martini/files/7447342/cnt-200-50-a470-CNP-f00-SNda.zip)
I have created a large diameter CNT using the following command:
`python3 martini-cnt-generator.py -nr 200 -rs 50 -bl 0.47 -bt CNP -fb 0 -fe 0`
When I open the generated .gro file in VMD, several beads appear adrift from the expected CNT surface. While most of the beads appear outside the CNT, some appear inside the CNT as well.

Any quick fixes will be helpful.

Thanks!
Raman

**Comment by martinvoegele** [comment]
Hi Raman, thanks for catching and reporting this! 

The coordinates were computed correctly but the output format (gro) is not compatible with atom names longer than 4 characters.

I have changed the output such that the maximum column width of the gro format is being satisfied. This change will lead to ambiguous atom names whenever there are more than 1000 atoms in a CNT. This restriction should be relevant for analysis but not for running the simulation. 

Please let me know whether you can successfully run a simulation of a large CNT created with the updated version.

**Comment by martinvoegele** [comment]
I am planning to keep the current numbering as default but introduce two options to use base-36 numbering encoded via all numbers 0-9 plus the 26 letters of the alphabet. The two new options are:
a) keep the leading C and F markers that distinguish functional groups and 
b) replace the leading letter and increase the number space for the atom names to four digits.

**Comment by martinvoegele** [comment]
Turns out option b) does not work because we want an atom name to start with a letter.
I am implementing option a) which increases the number of correctly named atoms to 36^3 = 46656.
